In [1]:
import pandas as pd       # для роботи з таблицями (DataFrame)
import numpy as np  
import matplotlib.pyplot as plt   # графіки
import seaborn as sns 
from sklearn.model_selection import train_test_split   # розбиття на train/test
from sklearn.metrics import accuracy_score, classification_report, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler      # нормалізація / масштабування фіч
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [10]:
pd.set_option("display.max_columns", None)

In [11]:
df_sackman_2020 = pd.read_csv('../data/sackmann/atp_matches_2020.csv')

In [12]:
df_tml_2020 = pd.read_csv('../data/tml/2020.csv')

In [13]:
df_sackman_2020

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2020-8888,Atp Cup,Hard,24,A,20200106,300,104925,NaN,NaN,Novak Djokovic,R,188.0,SRB,32.6,104745,NaN,NaN,Rafael Nadal,L,185.0,ESP,33.5,6-2 7-6(4),3,F,115.0,12.0,2.0,64.0,49.0,41.0,9.0,10.0,5.0,5.0,5.0,3.0,70.0,51.0,39.0,6.0,10.0,6.0,8.0,2.0,9055.0,1.0,9985.0
1,2020-8888,Atp Cup,Hard,24,A,20200106,299,105138,NaN,NaN,Roberto Bautista Agut,R,183.0,ESP,31.7,105583,NaN,NaN,Dusan Lajovic,R,183.0,SRB,29.5,7-5 6-1,3,F,97.0,2.0,1.0,59.0,44.0,29.0,10.0,10.0,3.0,5.0,2.0,1.0,57.0,35.0,21.0,6.0,9.0,5.0,10.0,10.0,2335.0,34.0,1251.0
2,2020-8888,Atp Cup,Hard,24,A,20200106,298,104925,NaN,NaN,Novak Djokovic,R,188.0,SRB,32.6,106421,NaN,NaN,Daniil Medvedev,R,198.0,RUS,23.9,6-1 5-7 6-4,3,SF,167.0,4.0,5.0,111.0,75.0,53.0,16.0,15.0,8.0,11.0,6.0,5.0,108.0,57.0,35.0,25.0,14.0,6.0,11.0,2.0,9055.0,5.0,5705.0
3,2020-8888,Atp Cup,Hard,24,A,20200106,297,105583,NaN,NaN,Dusan Lajovic,R,183.0,SRB,29.5,111575,NaN,NaN,Karen Khachanov,R,198.0,RUS,23.6,7-5 7-6(1),3,SF,108.0,1.0,1.0,67.0,48.0,38.0,14.0,12.0,0.0,0.0,9.0,3.0,79.0,54.0,39.0,14.0,12.0,0.0,1.0,34.0,1251.0,17.0,1840.0
4,2020-8888,Atp Cup,Hard,24,A,20200106,296,104745,NaN,NaN,Rafael Nadal,L,185.0,ESP,33.5,200282,NaN,NaN,Alex De Minaur,R,183.0,AUS,20.8,4-6 7-5 6-1,3,SF,133.0,5.0,3.0,84.0,61.0,48.0,10.0,15.0,1.0,3.0,6.0,1.0,75.0,55.0,37.0,10.0,14.0,1.0,5.0,1.0,9985.0,18.0,1775.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457,2020-7485,Antwerp,Hard,32,A,20201019,125,105554,NaN,NaN,Daniel Evans,R,175.0,GBR,30.4,106099,NaN,Q,Salvatore Caruso,R,185.0,ITA,27.8,6-2 3-6 6-3,3,R32,115.0,9.0,2.0,70.0,47.0,36.0,14.0,13.0,1.0,3.0,4.0,1.0,77.0,43.0,31.0,14.0,13.0,3.0,7.0,35.0,1384.0,79.0,802.0
1458,2020-7485,Antwerp,Hard,32,A,20201019,126,200267,NaN,WC,Zizou Bergs,R,185.0,BEL,21.3,105077,NaN,NaN,Albert Ramos,L,188.0,ESP,32.7,7-5 7-5,3,R32,102.0,7.0,2.0,77.0,54.0,33.0,13.0,12.0,6.0,9.0,1.0,3.0,66.0,45.0,27.0,10.0,12.0,4.0,9.0,528.0,58.0,45.0,1165.0
1459,2020-7485,Antwerp,Hard,32,A,20201019,128,126203,7.0,NaN,Taylor Fritz,R,196.0,USA,22.9,124187,NaN,NaN,Reilly Opelka,R,211.0,USA,23.1,7-6(5) 6-1,3,R32,67.0,10.0,1.0,59.0,44.0,39.0,6.0,10.0,0.0,0.0,19.0,3.0,58.0,37.0,30.0,5.0,9.0,3.0,5.0,28.0,1670.0,33.0,1402.0
1460,2020-7485,Antwerp,Hard,32,A,20201019,129,144750,NaN,Q,Lloyd Harris,R,193.0,RSA,23.6,144895,NaN,NaN,Corentin Moutet,L,180.0,FRA,21.5,7-5 6-2,3,R32,84.0,7.0,2.0,49.0,33.0,28.0,11.0,10.0,1.0,2.0,0.0,2.0,62.0,45.0,29.0,5.0,10.0,7.0,11.0,90.0,748.0,74.0,838.0
1461,2020-7485,Antwerp,Hard,32,A,20201019,130,200005,NaN,NaN,Ugo Humbert,L,188.0,FRA,22.3,106293,NaN,WC,Kimmer Coppejans,R,178.0,BEL,26.6,6-4 6-3,3,R32,73.0,3.0,2.0,53.0,26.0,24.0,17.0,10.0,3.0,3.0,2.0,0.0,49.0,32.0,26.0,7.0,9.0,2.0,4.0,38.0,1306.0,172.0,353.0

In [14]:
df_sackman_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          1462 non-null   object
 1   tourney_name        1462 non-null   object
 2   surface             1462 non-null   object
 3   draw_size           1462 non-null   int64
 4   tourney_level       1462 non-null   object
 5   tourney_date        1462 non-null   int64
 6   match_num           1462 non-null   int64
 7   winner_id           1462 non-null   int64
 8   winner_seed         578 non-null    float64
 9   winner_entry        233 non-null    object
 10  winner_name         1462 non-null   object
 11  winner_hand         1462 non-null   object
 12  winner_ht           1456 non-null   float64
 13  winner_ioc          1462 non-null   object
 14  winner_age          1462 non-null   float64
 15  loser_id            1462 non-null   int64
 16  loser_seed          325 non-null    float64
 17  loser_entry         327 non-null    object
 18  loser_name          1462 non-null   object
 19  loser_hand          1462 non-null   object
 20  loser_ht            1433 non-null   float64
 21  loser_ioc           1462 non-null   object
 22  loser_age           1462 non-null   float64
 23  score               1462 non-null   object
 24  best_of             1462 non-null   int64
 25  round               1462 non-null   object
 26  minutes             1421 non-null   float64
 27  w_ace               1415 non-null   float64
 28  w_df                1415 non-null   float64
 29  w_svpt              1415 non-null   float64
 30  w_1stIn             1415 non-null   float64
 31  w_1stWon            1415 non-null   float64
 32  w_2ndWon            1415 non-null   float64
 33  w_SvGms             1415 non-null   float64
 34  w_bpSaved           1415 non-null   float64
 35  w_bpFaced           1415 non-null   float64
 36  l_ace               1415 non-null   float64
 37  l_df                1415 non-null   float64
 38  l_svpt              1415 non-null   float64
 39  l_1stIn             1415 non-null   float64
 40  l_1stWon            1415 non-null   float64
 41  l_2ndWon            1415 non-null   float64
 42  l_SvGms             1415 non-null   float64
 43  l_bpSaved           1415 non-null   float64
 44  l_bpFaced           1415 non-null   float64
 45  winner_rank         1448 non-null   float64
 46  winner_rank_points  1448 non-null   float64
 47  loser_rank          1427 non-null   float64
 48  loser_rank_points   1427 non-null   float64
dtypes: float64(29), int64(6), object(14)
memory usage: 559.8+ KB

In [15]:
df_sackman_2020.describe()

,draw_size,tourney_date,match_num,winner_id,winner_seed,winner_ht,winner_age,loser_id,loser_seed,loser_ht,loser_age,best_of,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
count,1462.000000,1.462000e+03,1462.000000,1462.000000,578.000000,1456.000000,1462.000000,1462.000000,325.000000,1433.000000,1462.000000,1462.000000,1421.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1415.000000,1448.000000,1448.000000,1427.000000,1427.000000
mean,57.803010,2.020056e+07,317.791382,121983.125855,7.664360,187.544643,26.911765,121264.532832,8.735385,186.487090,27.252257,3.521204,118.978888,7.253004,2.681272,82.332862,52.008481,39.252297,16.546996,13.197173,3.795053,5.491873,5.345583,3.318728,85.643816,52.664311,35.047350,15.108834,12.915901,5.128622,9.130742,76.821133,1931.919890,107.234758,1188.539594
std,43.820298,3.894934e+02,291.604987,30605.749267,7.240231,7.160847,4.703324,30112.751939,7.596954,7.033142,4.632911,0.878226,45.322128,5.735780,2.285687,30.844459,20.435290,14.359078,6.704441,4.473874,3.144624,4.242279,5.125305,2.546770,31.333906,21.147317,15.534918,7.030709,4.465885,3.428043,4.392582,132.965820,2340.704825,172.371261,1374.026909
min,4.000000,2.020011e+07,1.000000,100644.000000,1.000000,170.000000,15.800000,100644.000000,1.000000,170.000000,16.100000,3.000000,0.000000,0.000000,0.000000,4.000000,3.000000,3.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,11.000000,8.000000,2.000000,1.000000,2.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,32.000000,2.020020e+07,214.250000,105379.000000,3.000000,183.000000,22.900000,105430.000000,4.000000,183.000000,23.325000,3.000000,85.000000,3.000000,1.000000,59.000000,36.500000,28.500000,12.000000,10.000000,1.000000,2.000000,2.000000,2.000000,63.000000,38.000000,24.000000,10.000000,10.000000,3.000000,6.000000,18.000000,688.250000,33.500000,543.000000
50%,32.000000,2.020031e+07,278.000000,106210.000000,5.000000,188.000000,26.900000,106078.000000,6.000000,185.000000,27.300000,3.000000,113.000000,6.000000,2.000000,77.000000,49.000000,37.000000,16.000000,12.000000,3.000000,5.000000,4.000000,3.000000,80.000000,49.000000,33.000000,14.000000,12.000000,4.000000,9.000000,44.000000,1124.000000,67.000000,838.000000
75%,128.000000,2.020093e+07,292.000000,126203.750000,9.000000,193.000000,30.300000,126203.000000,11.000000,191.000000,30.400000,5.000000,142.000000,10.000000,4.000000,99.000000,63.000000,47.000000,20.000000,15.000000,6.000000,8.000000,7.000000,4.000000,102.000000,64.000000,43.000000,19.000000,15.000000,7.000000,11.000000,87.000000,2051.250000,108.000000,1344.000000
max,128.000000,2.020112e+07,1701.000000,209874.000000,32.000000,211.000000,40.800000,209873.000000,32.000000,211.000000,41.500000,5.000000,365.000000,46.000000,16.000000,244.000000,161.000000,102.000000,44.000000,36.000000,19.000000,30.000000,52.000000,15.000000,215.000000,154.000000,104.000000,43.000000,36.000000,27.000000,35.000000,1671.000000,11830.000000,1752.000000,11830.000000

In [16]:
df_tml_2020.describe()

,draw_size,tourney_date,match_num,winner_seed,winner_ht,winner_age,winner_rank,winner_rank_points,loser_seed,loser_ht,loser_age,loser_rank,loser_rank_points,best_of,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
count,1466.000000,1.466000e+03,1466.000000,554.000000,1458.000000,1466.000000,1451.000000,1451.000000,310.000000,1432.000000,1465.000000,1428.000000,1428.000000,1466.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.00000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000,1389.000000
mean,55.950887,2.020056e+07,29.635061,7.687726,187.527435,26.970073,76.528601,1933.309442,8.719355,186.551676,27.293466,107.452381,1188.339636,3.519782,119.630670,7.258459,2.695464,82.434125,52.082793,39.286537,16.558675,13.151188,3.819294,5.50252,5.357811,3.335493,85.771778,52.746580,35.068395,15.135349,12.894888,5.138949,9.155508
std,44.278705,3.893614e+02,30.600205,7.322212,7.167733,4.700289,132.750369,2339.330673,7.723495,7.055841,4.632156,174.655825,1373.621500,0.877448,45.006416,5.758480,2.298067,31.059778,20.585372,14.477846,6.751799,4.515922,3.157905,4.25072,5.141875,2.557925,31.520825,21.293015,15.649679,7.044453,4.532039,3.442632,4.415261
min,4.000000,2.020010e+07,1.000000,1.000000,170.000000,15.855000,1.000000,1.000000,1.000000,170.000000,16.208000,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28.000000,2.020020e+07,8.000000,3.000000,183.000000,22.919000,18.000000,689.500000,4.000000,183.000000,23.379000,33.750000,544.500000,3.000000,85.000000,3.000000,1.000000,59.000000,36.000000,28.000000,12.000000,10.000000,1.000000,2.00000,2.000000,2.000000,63.000000,38.000000,24.000000,10.000000,10.000000,3.000000,6.000000
50%,32.000000,2.020031e+07,19.000000,5.000000,188.000000,26.992000,44.000000,1124.000000,6.000000,185.000000,27.296000,67.000000,835.000000,3.000000,114.000000,6.000000,2.000000,78.000000,49.000000,37.000000,16.000000,12.000000,3.000000,5.00000,4.000000,3.000000,81.000000,49.000000,33.000000,14.000000,12.000000,4.000000,9.000000
75%,128.000000,2.020093e+07,38.000000,9.000000,193.000000,30.402250,87.000000,2052.500000,10.000000,191.000000,30.470000,108.000000,1343.500000,5.000000,142.000000,10.000000,4.000000,99.000000,63.000000,47.000000,20.000000,15.000000,6.000000,8.00000,7.000000,4.000000,102.000000,64.000000,43.000000,19.000000,15.000000,7.000000,11.000000
max,128.000000,2.020112e+07,127.000000,32.000000,211.000000,40.893000,1671.000000,11830.000000,32.000000,211.000000,41.506000,1752.000000,11830.000000,5.000000,365.000000,46.000000,16.000000,244.000000,161.000000,102.000000,44.000000,36.000000,19.000000,30.00000,52.000000,15.000000,215.000000,154.000000,104.000000,43.000000,36.000000,27.000000,35.000000

In [17]:
df_tml_2020

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,winner_rank,winner_rank_points,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,loser_rank,loser_rank_points,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2020-8888,ATP Cup,Hard,24,A,O,20200103,1,D632,NaN,NaN,Steve Darcis,R,175.0,BEL,35.808,157.0,332.0,CJ60,NaN,NaN,Alexandr Cozbinov,R,188.0,MDA,24.684,NaN,NaN,6-4 6-7(4) 7-5,3,RR,190.0,8.0,2.0,113.0,66.0,43.0,21.0,17.0,8.0,14.0,2.0,2.0,116.0,72.0,42.0,18.0,17.0,6.0,14.0
1,2020-8888,ATP Cup,Hard,24,A,O,20200103,2,GB88,NaN,NaN,David Goffin,R,180.0,BEL,29.073,11.0,2335.0,A829,NaN,NaN,Radu Albot,R,175.0,MDA,30.144,46.0,1067.0,6-4 6-1,3,RR,82.0,6.0,3.0,54.0,30.0,22.0,15.0,8.0,5.0,5.0,3.0,2.0,63.0,39.0,23.0,10.0,9.0,7.0,11.0
2,2020-8888,ATP Cup,Hard,24,A,O,20200103,3,N771,NaN,NaN,Cameron Norrie,L,188.0,GBR,24.364,53.0,975.0,KC33,NaN,NaN,Dimitar Kuzmanov,R,183.0,BUL,26.434,423.0,80.0,6-2 3-6 6-2,3,RR,119.0,8.0,5.0,60.0,40.0,33.0,7.0,12.0,2.0,5.0,4.0,2.0,82.0,53.0,32.0,12.0,13.0,4.0,10.0
3,2020-8888,ATP Cup,Hard,24,A,O,20200103,4,D875,NaN,NaN,Grigor Dimitrov,R,191.0,BUL,28.635,20.0,1747.0,E687,NaN,NaN,Daniel Evans,R,175.0,GBR,29.615,42.0,1124.0,2-6 6-4 6-1,3,RR,136.0,3.0,4.0,81.0,50.0,29.0,19.0,13.0,3.0,7.0,1.0,0.0,83.0,53.0,32.0,13.0,12.0,3.0,8.0
4,2020-8888,ATP Cup,Hard,24,A,O,20200103,5,FB98,NaN,NaN,Taylor Fritz,R,196.0,USA,22.182,32.0,1315.0,DC76,NaN,NaN,Viktor Durasovic,R,185.0,NOR,22.793,332.0,117.0,6-2 6-2,3,RR,61.0,11.0,2.0,39.0,23.0,22.0,11.0,8.0,1.0,1.0,3.0,1.0,57.0,32.0,18.0,10.0,8.0,7.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1461,2020-605,Tour Finals,Hard,8,F,I,20201116,11,RE44,7.0,NaN,Andrey Rublev,R,188.0,RUS,23.075,8.0,3919.0,TB69,3.0,NaN,Dominic Thiem,R,185.0,AUT,27.203,3.0,9125.0,6-2 7-5,3,RR,74.0,11.0,0.0,52.0,35.0,28.0,11.0,10.0,0.0,1.0,10.0,3.0,70.0,50.0,33.0,7.0,10.0,6.0,10.0
1462,2020-605,Tour Finals,Hard,8,F,I,20201116,12,TE51,6.0,NaN,Stefanos Tsitsipas,R,193.0,GRE,22.264,6.0,5925.0,RE44,7.0,NaN,Andrey Rublev,R,188.0,RUS,23.075,8.0,3919.0,6-1 4-6 7-6(6),3,RR,115.0,10.0,0.0,83.0,57.0,46.0,15.0,15.0,0.0,1.0,6.0,2.0,95.0,59.0,44.0,17.0,14.0,7.0,9.0
1463,2020-605,Tour Finals,Hard,8,F,I,20201116,13,MM58,4.0,NaN,Daniil Medvedev,R,198.0,RUS,24.764,4.0,6970.0,N409,2.0,NaN,Rafael Nadal,L,185.0,ESP,34.456,2.0,9850.0,3-6 7-6(4) 6-3,3,SF,155.0,13.0,3.0,82.0,57.0,44.0,12.0,14.0,1.0,4.0,3.0,3.0,117.0,66.0,49.0,19.0,16.0,7.0,11.0
1464,2020-605,Tour Finals,Hard,8,F,I,20201116,14,TB69,3.0,NaN,Dominic Thiem,R,185.0,AUT,27.203,3.0,9125.0,D643,1.0,NaN,Novak Djokovic,R,188.0,SRB,33.489,1.0,11830.0,7-5 6-7(10) 7-6(5),3,SF,174.0,12.0,5.0,120.0,77.0,63.0,23.0,18.0,3.0,3.0,5.0,0.0,114.0,74.0,63.0,18.0,18.0,1.0,2.0
1465,2020-605,Tour Finals,Hard,8,F,I,20201116,15,MM58,4.0,NaN,Daniil Medvedev,R,198.0,RUS,24.764,4.0,6970.0,TB69,3.0,NaN,Dominic Thiem,R,185.0,AUT,27.203,3.0,9125.0,4-6 7-6(2) 6-4,3,F,162.0,12.0,3.0,110.0,66.0,51.0,24.0,16.0,3.0,4.0,6.0,1.0,117.0,85.0,63.0,14.0,16.0,8.0,9.0

In [18]:
df_tml_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1466 entries, 0 to 1465
Data columns (total 50 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          1466 non-null   object
 1   tourney_name        1466 non-null   object
 2   surface             1466 non-null   object
 3   draw_size           1466 non-null   int64
 4   tourney_level       1466 non-null   object
 5   indoor              1353 non-null   object
 6   tourney_date        1466 non-null   int64
 7   match_num           1466 non-null   int64
 8   winner_id           1466 non-null   object
 9   winner_seed         554 non-null    float64
 10  winner_entry        231 non-null    object
 11  winner_name         1466 non-null   object
 12  winner_hand         1463 non-null   object
 13  winner_ht           1458 non-null   float64
 14  winner_ioc          1466 non-null   object
 15  winner_age          1466 non-null   float64
 16  winner_rank         1451 non-null   float64
 17  winner_rank_points  1451 non-null   float64
 18  loser_id            1466 non-null   object
 19  loser_seed          310 non-null    float64
 20  loser_entry         315 non-null    object
 21  loser_name          1466 non-null   object
 22  loser_hand          1448 non-null   object
 23  loser_ht            1432 non-null   float64
 24  loser_ioc           1466 non-null   object
 25  loser_age           1465 non-null   float64
 26  loser_rank          1428 non-null   float64
 27  loser_rank_points   1428 non-null   float64
 28  score               1466 non-null   object
 29  best_of             1466 non-null   int64
 30  round               1466 non-null   object
 31  minutes             1389 non-null   float64
 32  w_ace               1389 non-null   float64
 33  w_df                1389 non-null   float64
 34  w_svpt              1389 non-null   float64
 35  w_1stIn             1389 non-null   float64
 36  w_1stWon            1389 non-null   float64
 37  w_2ndWon            1389 non-null   float64
 38  w_SvGms             1389 non-null   float64
 39  w_bpSaved           1389 non-null   float64
 40  w_bpFaced           1389 non-null   float64
 41  l_ace               1389 non-null   float64
 42  l_df                1389 non-null   float64
 43  l_svpt              1389 non-null   float64
 44  l_1stIn             1389 non-null   float64
 45  l_1stWon            1389 non-null   float64
 46  l_2ndWon            1389 non-null   float64
 47  l_SvGms             1389 non-null   float64
 48  l_bpSaved           1389 non-null   float64
 49  l_bpFaced           1389 non-null   float64
dtypes: float64(29), int64(4), object(17)
memory usage: 572.8+ KB

In [19]:
df_tml_2020.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'indoor', 'tourney_date', 'match_num', 'winner_id', 'winner_seed',
       'winner_entry', 'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc',
       'winner_age', 'winner_rank', 'winner_rank_points', 'loser_id',
       'loser_seed', 'loser_entry', 'loser_name', 'loser_hand', 'loser_ht',
       'loser_ioc', 'loser_age', 'loser_rank', 'loser_rank_points', 'score',
       'best_of', 'round', 'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn',
       'w_1stWon', 'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace',
       'l_df', 'l_svpt', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms',
       'l_bpSaved', 'l_bpFaced'],
      dtype='object')

In [20]:
df_sackman_2020.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points'],
      dtype='object')